apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: postgres
spec:
  type: state.postgresql
  version: v1
  metadata:
    - name: connectionString
      value: "host=localhost user=postgres password=password port=5433 connect_timeout=10 database=activity"